services:
  lemon-music:
    image: ghcr.io/jia070310/lemon-muisc:latest
    container_name: lemon-music
    ports:
      - "7983:7983"
    volumes:
      # 本机示例：当前目录下的 data / config
      # 飞牛 NAS 示例：
      #   - /vol1/1000/music:/data
      #   - /vol1/1000/lemon-music-config:/config
      - ./data:/data
      - ./config:/config
    environment:
      - PORT=7983
      - DOWNLOAD_PATH=/data
      - CONFIG_PATH=/config
    restart: unless-stopped
