services:
  lemon-music:
    image: ghcr.1ms.run/jia070310/lemon-muisc:latest
    container_name: lemon-music
    restart: unless-stopped
    ports:
      - "7983:7983"
    volumes:
      - "${wizard_music_path}:/music"
      - "${wizard_downloads_path}:/downloads"
      - "${wizard_config_path}:/config"
    environment:
      PORT: "7983"
      DOWNLOAD_PATH: /music
      CONFIG_PATH: /config
      MUSIC_HOST_PATH: "${wizard_music_path}"
      DOWNLOADS_HOST_PATH: "${wizard_downloads_path}"
